### ISSUE TITLE
Can't connect to mariaDB

### ISSUE THREAD

**Issue by GH-Richard** [phundament/app#194]
I get the following error: 
    SQLSTATE[HY000] [1045] Access denied for user 'user'@'172.17.0.3' (using password: YES)
And when I change the variables:
- DB_PORT_3306_TCP_ADDR=myIp
- DB_PORT_3306_TCP_PORT=myPort

within the .env file according to the IP+Port I need, there is still the same error.

**Comment by schmunk42** [comment]
Some questions from my side :)

Are you running phundament inside Docker?
Which database do you want to use, also Docker?
Do you have the user `user`?
Can you set your user here?
```
DB_ENV_MYSQL_USER=dev
DB_ENV_MYSQL_PASSWORD=dev123
```

Can you run `docker-compose run php yii db/create`?
Like so:

```
Kraftbuch:app tobias$ docker-compose run php yii db/create
Creating app_mariadb_1
Checking database connection on DSN 'mysql:host=172.17.0.2;port=3306' with user 'admin'......... [OK]
Creating database 'dev-phundament-4' and granting permissions to user 'dev' on DSN 'mysql:host=172.17.0.2;port=3306' with user 'admin'. [OK]
Kraftbuch:app tobias$ 
```

**Comment by GH-Richard** [comment]
Thx for your response. Yes, I run phunament inside Docker and I use mysql.
my DB_ENV_MYSQL_USER is actually dev, I've just copied the varName and wrote a random userName. But in my case its "dev" as well. 
Your command returns:
Interactive mode is not yet supported on Windows. Please pass the -d flag
when using 'docker-compose run'.

**Comment by GH-Richard** [comment]
I execute docker-compose within the "Docker Quickstart Terminal".
My docker-compose.yml contains:
```
# Phundament 4 - Application stack

php:
  build: .
  links:
    - 'mariadb'


nginx:
  image: phundament/nginx-one:1.9
  links:
    - 'php:PHPFPM'

mariadb:
  image: 'tutum/mariadb:10.1'
  environment:
    MARIADB_PASS: secretadmin
```

**Comment by schmunk42** [comment]
Use

```
php:
  build: .
  links:
    - 'mariadb:DB'
```

This will prefix ENV variables from the database container with `DB_` - Phundament expects this in its config.

Note that links will go away in a future version of **Docker**.
